#!/usr/bin/env bash
#
# AutoEdit — one-command VPS deploy (Ubuntu/Debian, e.g. Hostinger).
#
# Usage (run as root on the VPS):
#   curl -fsSL https://raw.githubusercontent.com/gavoekoffi2/auto-edit/<branch>/deploy/deploy.sh | bash
# or, after cloning:
#   bash deploy/deploy.sh
#
# It installs Docker, clones/updates the repo, writes a production .env
# (generating a SECRET_KEY on first run), and starts the full stack.
#
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/gavoekoffi2/auto-edit.git}"
BRANCH="${BRANCH:-claude/autoedit-saas-platform-6fEmt}"
APP_DIR="${APP_DIR:-/opt/autoedit}"
# Public origin(s) of the frontend, comma-separated (Netlify + your domain).
CORS_ORIGINS_DEFAULT="https://tubular-nasturtium-cfb67e.netlify.app"

log() { echo -e "\033[1;36m[deploy]\033[0m $*"; }

# --- 1. Docker -------------------------------------------------------------- #
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
fi
if ! docker compose version >/dev/null 2>&1; then
  log "Installing Docker Compose plugin..."
  apt-get update -y && apt-get install -y docker-compose-plugin
fi

# --- 2. Clone / update repo ------------------------------------------------- #
if [ -d "$APP_DIR/.git" ]; then
  log "Updating existing checkout in $APP_DIR..."
  git -C "$APP_DIR" fetch origin "$BRANCH"
  git -C "$APP_DIR" checkout "$BRANCH"
  git -C "$APP_DIR" reset --hard "origin/$BRANCH"
else
  log "Cloning $REPO_URL ($BRANCH) into $APP_DIR..."
  git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
fi
cd "$APP_DIR"

# --- 3. .env (generated once, then preserved) ------------------------------- #
if [ ! -f .env ]; then
  log "Creating .env (generating SECRET_KEY)..."
  SECRET_KEY="$(python3 -c 'import secrets;print(secrets.token_urlsafe(48))' 2>/dev/null || openssl rand -base64 48 | tr -d '\n')"
  POSTGRES_PASSWORD="$(openssl rand -hex 16)"
  cat > .env <<EOF
# --- Generated by deploy.sh on $(date -u +%FT%TZ) ---
POSTGRES_USER=autoedit
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=autoedit

SECRET_KEY=${SECRET_KEY}

# Frontend origins allowed by CORS (add your custom domain here too).
CORS_ORIGINS=${CORS_ORIGINS:-$CORS_ORIGINS_DEFAULT}

WHISPER_MODEL=base
REMOTION_CONCURRENCY=2

# FedaPay — fill these in to enable payments.
FEDAPAY_ENV=sandbox
FEDAPAY_SECRET_KEY=
FEDAPAY_PUBLIC_KEY=
EOF
  log ".env created. Edit it to add FedaPay keys when ready."
else
  log ".env already exists — leaving it untouched."
fi

# --- 4. Build & start (production config only, no dev override) ------------- #
log "Building and starting containers (this can take several minutes the first time)..."
docker compose -f docker-compose.yml up -d --build

log "Waiting for the API to become healthy..."
for i in $(seq 1 30); do
  if curl -fsS http://127.0.0.1:8000/api/health >/dev/null 2>&1; then
    log "Backend is UP. /api/health responds."
    break
  fi
  sleep 3
done

cat <<'NEXT'

================================================================
 AutoEdit stack is running.

   Backend API : http://127.0.0.1:8000/api  (health: /api/health)
   Frontend    : http://127.0.0.1:3000
   Bundled nginx (frontend+API): http://127.0.0.1:80

 NEXT STEP — expose it over your existing HTTPS host
 (srv1305401.hstgr.cloud already has a valid TLS certificate):

 Point your reverse proxy so that:
   https://srv1305401.hstgr.cloud/api/  ->  http://127.0.0.1:8000/api/

 See deploy/reverse-proxy.md for ready-to-paste Caddy / Nginx snippets.

 Verify:  curl https://srv1305401.hstgr.cloud/api/health
          # should return {"status":"healthy",...} (our FastAPI),
          # NOT {"ok":true} (the old stub).
================================================================
NEXT
